services:
  db:
    image: postgres:13
    container_name: postgres_database  # Add this line to give it a fixed name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${DB_PORT_HOST}:5432"
    networks:
      postgres_network:
        aliases:
          - postgres_db  # This creates a network alias
    restart: always

volumes:
  postgres_data:
    external: true

networks:
  postgres_network:
    external: true
    name: postgres_network