# Generated by Django 5.1.6 on 2025-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_produk_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='foto',
            field=models.ImageField(upload_to='produk/'),
        ),
    ]
