# Generated by Django 5.1.6 on 2025-05-07 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('produk', '0002_satuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriproduk',
            name='toko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='authentication.toko'),
        ),
        migrations.AlterUniqueTogether(
            name='kategoriproduk',
            unique_together={('nama', 'toko')},
        ),
    ]
