# Generated by Django 5.1.6 on 2025-05-08 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('produk', '0003_kategoriproduk_toko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satuan',
            name='toko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satuan', to='authentication.toko'),
        ),
        migrations.AlterUniqueTogether(
            name='satuan',
            unique_together={('nama', 'toko')},
        ),
    ]
