# Generated by Django 5.1.6 on 2025-03-24 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produk_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Pemilik'}, on_delete=django.db.models.deletion.CASCADE, related_name='produk', to=settings.AUTH_USER_MODEL),
        ),
    ]
