# Generated by Django 5.1.6 on 2025-04-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='stok',
            field=models.IntegerField(),
        ),
    ]
