# Generated by Django 5.1.6 on 2025-04-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_alter_produk_stok'),
        ('produk', '0005_alter_produk_user'),
    ]

    operations = [
    ]
