# Generated by Django 5.1.6 on 2025-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_merge_0005_alter_produk_stok_0005_alter_produk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
