# Generated by Django 5.1.6 on 2025-02-27 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('harga_modal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.DecimalField(decimal_places=3, max_digits=10)),
                ('satuan', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilogram'), ('LITER', 'Liter'), ('METER', 'Meter'), ('PACK', 'Pack'), ('BOTOL', 'Botol'), ('LAINNYA', 'Lainnya')], max_length=10)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='api.kategoriproduk')),
            ],
        ),
    ]
