# Generated by Django 5.1.6 on 2025-02-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='produk',
            name='satuan',
            field=models.CharField(max_length=10),
        ),
    ]
