# Generated by Django 5.1.6 on 2025-04-22 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HutangPiutangReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_hutang', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_piutang', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('jumlah_transaksi_hutang', models.IntegerField(default=0)),
                ('jumlah_transaksi_piutang', models.IntegerField(default=0)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hutang_piutang_reports', to='authentication.toko')),
            ],
            options={
                'ordering': ['-tanggal'],
                'unique_together': {('toko', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='DetailHutangPiutang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaksi_id', models.CharField(max_length=10)),
                ('jenis', models.CharField(choices=[('hutang', 'Hutang'), ('piutang', 'Piutang')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_transaksi', models.DateTimeField()),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='laporan.hutangpiutangreport')),
            ],
            options={
                'ordering': ['-tanggal_transaksi'],
            },
        ),
    ]
