# Generated by Django 5.1.6 on 2025-04-28 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('laporan', '0001_initial'),
        ('transaksi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArusKasReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bulan', models.IntegerField(default=1)),
                ('tahun', models.IntegerField(default=2025)),
                ('total_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aruskas_reports', to='authentication.toko')),
            ],
            options={
                'ordering': ['-tahun', '-bulan'],
                'unique_together': {('toko', 'bulan', 'tahun')},
            },
        ),
        migrations.CreateModel(
            name='DetailArusKas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(choices=[('inflow', 'Masuk'), ('outflow', 'Keluar')], max_length=10)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategori', models.CharField(max_length=50)),
                ('tanggal_transaksi', models.DateTimeField()),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='laporan.aruskasreport')),
                ('transaksi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaksi.transaksi')),
            ],
            options={
                'ordering': ['-tanggal_transaksi'],
            },
        ),
    ]
