# Generated by Django 5.1.6 on 2025-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailaruskas',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailhutangpiutang',
            name='keterangan',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
