# Generated by Django 5.1.6 on 2025-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('Pemilik', 'Pemilik'), ('Administrator', 'Administrator'), ('Karyawan', 'Karyawan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Pemilik', 'Pemilik'), ('Administrator', 'Administrator'), ('Karyawan', 'Karyawan')], default='Pemilik', max_length=20),
        ),
    ]
