# Generated by Django 5.1.6 on 2025-03-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Pemilik', 'Pemilik'), ('Karyawan', 'Karyawan')], default='Pemilik', max_length=20),
        ),
    ]
