# Generated by Django 5.1.6 on 2025-03-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0004_produk_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM_LUNAS', 'Belum Lunas')], max_length=20)),
                ('tanggalTransaksi', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='transaksi/')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('namaPelanggan', models.CharField(blank=True, max_length=255, null=True)),
                ('nomorTeleponPelanggan', models.CharField(blank=True, max_length=15, null=True)),
                ('daftarProduk', models.ManyToManyField(related_name='transaksi', to='produk.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('PEMBELIAN_STOK', 'Pembelian Stok'), ('PENGELUARAN_DI_LUAR_USAHA', 'Pengeluaran Di Luar Usaha'), ('PEMBELIAN_BAHAN_BAKU', 'Pembelian Bahan Baku'), ('BIAYA_OPERASIONAL', 'Biaya Operasional'), ('GAJI_ATAU_BONUS_KARYAWAN', 'Gaji Atau Bonus Karyawan'), ('PEMBERIAN_UTANG', 'Pemberian Utang'), ('PEMBAYARAN_UTANG_ATAU_CICILAN', 'Pembayaran Utang Atau Cicilan'), ('PENGELUARAN_LAIN', 'Pengeluaran Lain')], max_length=50)),
                ('totalPengeluaran', models.FloatField()),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pengeluaran', to='transaksi.transaksi')),
            ],
        ),
        migrations.CreateModel(
            name='Pemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('PENJUALAN', 'Penjualan'), ('PENAMBAHAN_MODAL', 'Penambahan Modal'), ('PENDAPATAN_DI_LUAR_USAHA', 'Pendapatan Di Luar Usaha'), ('PENDAPATAN_JASA_ATAU_KOMISI', 'Pendapatan Jasa Atau Komisi'), ('TERIMA_PINJAMAN', 'Terima Pinjaman'), ('PENAGIHAN_UTANG_ATAU_CICILAN', 'Penagihan Utang Atau Cicilan'), ('PENDAPATAN_LAIN', 'Pendapatan Lain')], max_length=50)),
                ('totalPemasukan', models.FloatField()),
                ('hargaModal', models.FloatField()),
                ('transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pemasukan', to='transaksi.transaksi')),
            ],
        ),
    ]
