# Generated by Django 5.1.6 on 2025-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_alter_transaksiitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
