# Generated by Django 5.1.6 on 2025-04-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_alter_transaksi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
