name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t my-django-app .
        docker tag my-django-app christophernw/dkn-pos-umkm-be:latest
        docker push christophernw/dkn-pos-umkm-be:latest

    - name: Deploy to Cloud Server via SSH
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd django-be
          docker pull christophernw/dkn-pos-umkm-be:latest
          docker stop myproject_django || true
          docker rm myproject_django || true
          docker run -d --name myproject_django -p 8000:8000 christophernw/dkn-pos-umkm-be:latest
        EOF
