name: Deploy Django App

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "BRANCH=main" >> $GITHUB_ENV
          echo "PORT=8000" >> $GITHUB_ENV
          echo "CONTAINER_NAME=myproject_django_main" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
          echo "BRANCH=staging" >> $GITHUB_ENV
          echo "PORT=8001" >> $GITHUB_ENV
          echo "CONTAINER_NAME=myproject_django_staging" >> $GITHUB_ENV
        fi

    - name: Build and Push Docker Image
      run: |
        docker build -t my-django-app .
        docker tag my-django-app christophernw/dkn-pos-umkm-be:${{ env.BRANCH }}
        docker push christophernw/dkn-pos-umkm-be:${{ env.BRANCH }}

    - name: Deploy to Cloud Server via SSH
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          cd django-be
          docker pull christophernw/dkn-pos-umkm-be:${{ env.BRANCH }}
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          docker run -d --name ${{ env.CONTAINER_NAME }} -p ${{ env.PORT }}:8000 christophernw/dkn-pos-umkm-be:${{ env.BRANCH }}
        EOF