name: Deploy Django App

on:
  push:
    branches:
      - main
      - staging

  pull_request:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Add this step to set version
    - name: Set version
      id: version
      run: |
        # Set default version from version.txt
        VERSION=$(cat version.txt)
        
        # If this is a tagged release, use the tag
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Set environment variables
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ] || [ "${{ github.base_ref }}" == "main" ]; then
          echo "BRANCH=main" >> $GITHUB_ENV
          echo "PORT=8000" >> $GITHUB_ENV
          echo "DB_PORT_HOST=5432" >> $GITHUB_ENV
          echo "SENTRY_DSN_VAR=SENTRY_DSN_PROD" >> $GITHUB_ENV
          echo "SEEDING_MODE=production" >> $GITHUB_ENV
        elif [ "${{ github.ref }}" == "refs/heads/staging" ] || [ "${{ github.base_ref }}" == "staging" ]; then
          echo "BRANCH=staging" >> $GITHUB_ENV
          echo "PORT=8001" >> $GITHUB_ENV
          echo "DB_PORT_HOST=5433" >> $GITHUB_ENV
          echo "SENTRY_DSN_VAR=SENTRY_DSN_STAGING" >> $GITHUB_ENV
          echo "SEEDING_MODE=server" >> $GITHUB_ENV
        else
          echo "BRANCH=dev" >> $GITHUB_ENV
          echo "PORT=8002" >> $GITHUB_ENV
          echo "DB_PORT_HOST=5434" >> $GITHUB_ENV
          echo "SENTRY_DSN_VAR=SENTRY_DSN_DEV" >> $GITHUB_ENV
          echo "SEEDING_MODE=local" >> $GITHUB_ENV
        fi

    # Update this step to tag with version
    - name: Build and Push Docker Image
      run: |
        # Build the image with version as build arg
        docker build -t my-django-app --build-arg VERSION=${{ env.VERSION }} .
        
        # Tag with version and environment
        docker tag my-django-app christophernw/dkn-pos-umkm-be:${{ env.VERSION }}-${{ env.ENV }}
        
        # Also tag with branch name for backward compatibility
        docker tag my-django-app christophernw/dkn-pos-umkm-be:${{ env.BRANCH }}
        
        # Push both tags
        docker push christophernw/dkn-pos-umkm-be:${{ env.VERSION }}-${{ env.ENV }}
        docker push christophernw/dkn-pos-umkm-be:${{ env.BRANCH }}

    - name: Copy docker-compose files
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          # Create directories if they don't exist
          mkdir -p ~/postgres-db-${{ env.BRANCH }}
          mkdir -p ~/django-be-${{ env.BRANCH }}
        EOF
        
        # Then copy the docker-compose files
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.prod.${{ env.BRANCH }}.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/django-be-${{ env.BRANCH }}/docker-compose.yml
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.db.${{ env.BRANCH }}.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/postgres-db-${{ env.BRANCH }}/docker-compose.yml

    # Update the deploy step to pass VERSION to the environment and run database seeding
    - name: Deploy database and web application
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          cd ~/django-be-${{ env.BRANCH }}
          echo "BRANCH=${{ env.BRANCH }}" > .env
          echo "PORT=${{ env.PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "VERSION=${{ env.VERSION }}" >> .env
          
          # Dynamically choose correct Sentry DSN based on environment
          if [ "${{ env.BRANCH }}" == "main" ]; then
            echo "SENTRY_DSN_PROD=${{ secrets.SENTRY_DSN_PROD }}" >> .env
          elif [ "${{ env.BRANCH }}" == "staging" ]; then
            echo "SENTRY_DSN_STAGING=${{ secrets.SENTRY_DSN_STAGING }}" >> .env
          else
            echo "SENTRY_DSN_DEV=${{ secrets.SENTRY_DSN_DEV }}" >> .env
          fi
          
          docker-compose --env-file .env pull
          docker-compose --env-file .env down --remove-orphans
          docker-compose --env-file .env up -d
          
          # Wait for the database and application to be ready
          sleep 10
          
          # Run database migrations
          docker-compose --env-file .env exec -T web python manage.py migrate
          
          # Only run automatic seeding for non-production environments
          if [ "${{ env.BRANCH }}" != "main" ]; then
            echo "Running automatic seeding for ${{ env.BRANCH }} environment..."
            docker-compose --env-file .env exec -T web python manage.py seed_database --mode=${{ env.SEEDING_MODE }} --email=gg.gaming1030@gmail.com --clean
          else
            echo "Production environment detected. Skipping automatic seeding."
            echo "Use the Manual Production Seeding workflow to seed production data."
          fi
        EOF
